apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml_project
  labels:
    app: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
        - name: jb
          image: jb/ml_project:<VERSION>
          ports:

            - containerPort: 1313
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2